name: teluric
description: "Teluric"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  fl_chart: ^1.2.0
  flutter_animate: ^4.5.0
  google_fonts: ^8.1.0
  font_awesome_flutter: ^11.0.0
  intl: ^0.20.2
  http: ^1.2.1
  shared_preferences: ^2.5.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/